import { ArrowRight, Check, CircleAlert, LockKeyhole, Mail, Sparkles } from 'lucide-react'
import { useState } from 'react'
import type { FormEvent } from 'react'
import { useNavigate } from 'react-router-dom'
import { useAuth } from './useAuth'
import { isSupabaseConfigured } from '../lib/supabase'

export function Login() {
  const { signIn } = useAuth()
  const navigate = useNavigate()
  const [email, setEmail] = useState('')
  const [message, setMessage] = useState('')
  const [status, setStatus] = useState<'idle' | 'loading' | 'success' | 'error'>('idle')
  const submit = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); setStatus('loading'); setMessage(''); try { const mode = await signIn(email); if (mode === 'local') navigate('/dashboard'); else { setStatus('success'); setMessage('Te hemos enviado un enlace seguro. Revisa tu bandeja de entrada y también la carpeta de spam.') } } catch { setStatus('error'); setMessage('No hemos podido enviar el enlace. Comprueba la configuración de Supabase o inténtalo de nuevo.') } }
  return <main className="auth-screen"><div className="auth-brand-corner"><span className="product-mark"><Sparkles size={16} /> dexyn</span><span>Site OS</span></div><section className="auth-hero"><div className="auth-hero-orbit auth-orbit-one" /><div className="auth-hero-orbit auth-orbit-two" /><div className="auth-hero-content"><span className="eyebrow">The operating system for better websites</span><h1>Tu mejor trabajo merece un lugar a su altura.</h1><p>Diseña, publica y gestiona las webs de tus clientes con un sistema hecho para equipos pequeños que cuidan cada detalle.</p><div className="auth-proof"><span><Check size={13} /> Editor visual</span><span><Check size={13} /> Publicación rápida</span><span><Check size={13} /> Un workspace</span></div></div><div className="auth-hero-footer"><span>DEXYN / 2026</span><span>Built for small teams with high standards.</span></div></section><section className="auth-panel"><div className="auth-form"><div className="auth-form-header"><span className="auth-kicker">{isSupabaseConfigured ? 'Secure workspace access' : 'Workspace demo'}</span><span className={`auth-mode ${isSupabaseConfigured ? 'is-live' : ''}`}><i />{isSupabaseConfigured ? 'Live auth' : 'Local mode'}</span></div><h2>Bienvenido de nuevo.</h2><p className="auth-intro">{isSupabaseConfigured ? 'Recibe un enlace seguro en tu email para entrar a tu workspace.' : 'Prueba el workspace localmente. Tu sesión se guardará en este navegador.'}</p><form onSubmit={submit}><label htmlFor="login-email">Email profesional</label><div className="auth-input-wrap"><Mail size={17} /><input id="login-email" type="email" required autoComplete="email" placeholder="tu@agencia.com" value={email} onChange={(event) => setEmail(event.target.value)} /></div><button className="saas-button saas-button-primary auth-submit" type="submit" disabled={status === 'loading'}>{status === 'loading' ? 'Enviando enlace...' : isSupabaseConfigured ? 'Enviar enlace de acceso' : 'Entrar al workspace'} {status !== 'loading' && <ArrowRight size={16} />}</button></form>{message && <p className={`auth-feedback auth-feedback-${status}`} role={status === 'error' ? 'alert' : 'status'}>{status === 'success' ? <Check size={16} /> : status === 'error' ? <CircleAlert size={16} /> : <Mail size={16} />}{message}</p>}<div className="auth-divider"><span>Acceso protegido</span></div><small className="auth-security"><LockKeyhole size={14} /><span>No compartimos tu email. {isSupabaseConfigured ? 'La autenticación se gestiona con Supabase.' : 'Activa Supabase para usar magic links reales.'}</span></small><a className="auth-back-link" href="/">← Volver al sitio público</a></div></section></main>
}
